takes out some workflows for now

diff --git a/.github/workflows/documentation.yaml b/.github/workflows/documentation.yaml
--- a/.github/workflows/documentation.yaml
+++ b/.github/workflows/documentation.yaml
@@ -21,56 +21,56 @@ concurrency:
   cancel-in-progress: false
 
 jobs:
-  TruffleHog:
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: TruffleHog OSS
-        id: trufflehog
-        uses: trufflesecurity/trufflehog@main
-        continue-on-error: true
-        with:
-          path: .
-          base: "${{ github.event.repository.default_branch }}"
-          head: HEAD
-          extra_args: --debug
-
-      - name: Scan Results Status
-        if: steps.trufflehog.outcome == 'failure'
-        run: exit 1
-  Format-Black:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
-      - name: Format with Black
-        uses: psf/black@stable
-        with:
-          options: "--verbose"
-          src: "./forge"
-          version: "~= 24.2"
-      - name: Commit files
-        run: |
-          git add .
-          git config --local user.email "github-actions[bot]@users.noreply.github.com"
-          git config --local user.name "github-actions[bot]"
-          git commit -a -m "Formatted with Black"
-      - name: Push changes
-        uses: ad-m/github-push-action@master
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          branch: ${{ github.ref }}
+#  TruffleHog:
+#    runs-on: ubuntu-latest
+#    defaults:
+#      run:
+#        shell: bash
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#        with:
+#          fetch-depth: 0
+#
+#      - name: TruffleHog OSS
+#        id: trufflehog
+#        uses: trufflesecurity/trufflehog@main
+#        continue-on-error: true
+#        with:
+#          path: .
+#          base: "${{ github.event.repository.default_branch }}"
+#          head: HEAD
+#          extra_args: --debug
+#
+#      - name: Scan Results Status
+#        if: steps.trufflehog.outcome == 'failure'
+#        run: exit 1
+#  Format-Black:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4
+#        with:
+#          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
+#      - name: Format with Black
+#        uses: psf/black@stable
+#        with:
+#          options: "--verbose"
+#          src: "./forge"
+#          version: "~= 24.2"
+#      - name: Commit files
+#        run: |
+#          git add .
+#          git config --local user.email "github-actions[bot]@users.noreply.github.com"
+#          git config --local user.name "github-actions[bot]"
+#          git commit -a -m "Formatted with Black"
+#      - name: Push changes
+#        uses: ad-m/github-push-action@master
+#        with:
+#          github_token: ${{ secrets.GITHUB_TOKEN }}
+#          branch: ${{ github.ref }}
 
   Build-Deploy-Documentation:
-    needs: Format-Black
+#    needs: Format-Black
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
